version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - micros-net

  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    networks:
      - idrl-net

networks:
  idrl-net:
    driver: bridge

