version: '3'

services:
  api:
    container_name: 'idrl-api'
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "80:5050"
