services:

  api:
    container_name: 'idrl-api'
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "80:5050"
