# Usar la imagen oficial de Ubuntu 18.04 como base
FROM ubuntu:18.04

# Actualizar el sistema e instalar dependencias
RUN apt-get update && \
    apt-get install -y ffmpeg

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /scripts

